create_clock - name clk -period 10 -waveform {0 5} [get_ports "clk"]
set_clock_transition -rise 0.1 [get_clocks "clk"]
set_clock_transition -fall 0.1 [get_clocks "clk"]
set_clock_uncertainty 0.01 [get_clocks "clk"]
set_input_delay -max 1.0 [get_ports "rst"] -clock [get_clocks "clk"]
set_input_delay -max 1.0 [get_ports "rst_min"] -clock [get_clocks "clk"]
set_input_delay -max 1.0 [get_ports "rst_hr"] -clock [get_clocks "clk"]
set_input_delay -max 1.0 [get_ports "a_min"] -clock [get_clocks "clk"]
set_input_delay -max 1.0 [get_ports "a_hr"] -clock [get_clocks "clk"]
set_output_delay -max 1.0 [get_ports "sec"] -clock [get_clocks "clk"]
set_output_delay -max 1.0 [get_ports "min"] -clock [get_clocks "clk"]
set_output_delay -max 1.0 [get_ports "hr"] -clock [get_clocks "clk"]
set_output_delay -max 1.0 [get_ports "alarm_flag"] -clock [get_clocks "clk"]
